[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.2.2"

[[redirects]] 
  from = "https://efileonlinelegalcourier.netlify.app/homepage/aboutus"
  to = "/contact/"

[[redirects]]  
  from = "/homepage/aboutus"
  to = "/contact/"

